### ISSUE TITLE
Add sourceid support

### ISSUE THREAD

**Issue by eightysteele** [VertNet/Darwin-Core-Engine#1]
The VN bulkloader requires a sourceid from which datastore keys are constructed. The sourceid is the link between records published in VN and their original version at the source. 

The bulkloader needs a command line parameter that defines the column in the csv file that is the sourceid.

**Comment by eightysteele** [comment]
In the absence of a sourceid command line parameter, the bulkloader should look for a sourceid column in the CSV file.

**Comment by datadavev** [comment]
sourceid should be a managed value. What is the format / acceptable chars? who creates them? who assigns them? How are duplicates avoided? 

One solution might be to require that the sourceid is something generated from a reputable source such as EZID?

**Comment by eightysteele** [comment]
> sourceid should be a managed value. 

Agreed. The sourceid should be managed by the publisher.

> What is the format / acceptable chars? 

Thinking any string 500 bytes or less (since that's the max size of an App Engine key_name).

> who creates them? who assigns them? 

Publishers. If the publisher doesn't provide a sourceid for a record, the bulkloader can:
1) Generate a UUID locally
2) Allocate a unique integer key from the datastore
3) Generate a GUID via web service (e.g., EZID)

Right now we're leaning towards 2. For any generated sourceid, the CSV file would be re-written to include the sourceid column.

> How are duplicates avoided?

Right, so upon detecting a duplicate, the bulkloader will simply ignore the record and report the duplicate to the user. It's then up to the publisher to fix the duplicate and re-run the bulkloader.

**Comment by datadavev** [comment]
I would strongly prefer that the sourceid should be generated by a service like EZID. Then it can be reliably used to cross reference between different systems and is not tied specifically to vertnet infrastructure (one less thing for vertnet to maintain).

**Comment by eightysteele** [comment]
> I would strongly prefer that the sourceid should be generated by a service like EZID. Then it can be reliably used to cross reference between different systems and is not tied specifically to vertnet infrastructure (one less thing for vertnet to maintain).

Well, the _sourceid_ in this context is literally the id of a record at the publisher source, like a database row id or something. In most cases it will already exist. It's not something that VertNet will generate for every record.

Aside from _sourceid_, we could think about assigning an EZID to each VertNet record to handle your use case. I added issue #8 for this.

**Comment by datadavev** [comment]
ah, my mistake. I was interpreting it as an identifier for the collection from which the record is being pulled, not for the individual record.
