### ISSUE TITLE
Judicious choice of full-text indexing

### ISSUE THREAD

**Issue by tucotuco** [VertNet/Darwin-Core-Engine#14]
Decide what needs to be available for full text search and limit to those fields. Some, such as GeoreferencingVerificationStatus and other single-word controlled vocabularies are completely covered by the term search.

**Comment by eightysteele** [comment]
Right now full text for a record (used for indexing) contains a lot of garbage values. Need a less naive algorithm for generating full text.

See https://github.com/VertNet/Software/blob/master/vertnet/publishing/tools/bulkload_helper.py#L75

**Comment by eightysteele** [comment]
@tucotuco: One fast improvement is to ignore stop words:

http://www.textfixer.com/resources/common-english-words.txt

Also, maybe ignore a set of fields?

**Comment by tucotuco** [comment]
Here's a real-world example to illustrate field contents that aren't that useful to index.

This is from georeferenceRemarks:
"J. Jerolimo, 2004: georeferenced from textual locality description, i.e., retrospective georeferencing; elevation estimated from map"

**Comment by tucotuco** [comment]
Here is the list of fields. An X in front signifies that it probably is better to not be included in full-text indexing:

X type
X modified
X language
X rights
X rightsHolder
X accessRights
bibliographicCitation
X institutionID
X collectionID
X datasetID
institutionCode
collectionCode
datasetName
ownerInstitutionCode
X basisOfRecord
informationWithheld
dataGeneralizations
(special) dynamicProperties
X occurrenceID
catalogNumber
X occurrenceDetails
occurrenceRemarks
recordNumber
recordedBy
X individualID
X individualCount
sex
lifeStage
reproductiveCondition
behavior
establishmentMeans
occurrenceStatus
preparations
X disposition
otherCatalogNumbers
previousIdentifications
associatedMedia
associatedReferences
associatedOccurrences
associatedSequences
associatedTaxa
X eventID
samplingProtocol
samplingEffort
X eventDate
X eventTime
X startDayOfYear
X endDayOfYear
X year
X month
X day
X verbatimEventDate
habitat
fieldNumber
X fieldNotes
eventRemarks
X locationID
X higherGeographyID
higherGeography
continent
waterBody
islandGroup
island
country
countryCode
stateProvince
county
municipality
locality
verbatimLocality
verbatimElevation
X minimumElevationInMeters
X maximumElevationInMeters
verbatimDepth
X minimumDepthInMeters
X maximumDepthInMeters
X minimumDistanceAboveSurfaceInMeters
X maximumDistanceAboveSurfaceInMeters
locationAccordingTo
locationRemarks
X verbatimCoordinates
X verbatimLatitude
X verbatimLongitude
verbatimCoordinateSystem
verbatimSRS
X decimalLatitude
X decimalLongitude
geodeticDatum
X coordinateUncertaintyInMeters
X coordinatePrecision
X pointRadiusSpatialFit
X footprintWKT
X footprintSRS
X footprintSpatialFit
georeferencedBy
georeferenceProtocol
georeferenceSources
X georeferenceVerificationStatus
X georeferenceRemarks
X geologicalContextID
EarliestEonOrLowestEonothem
LatestEonOrHighestEonothem
EarliestEraOrLowestErathem
LatestEraOrHighestErathem
EarliestPeriodOrLowestSystem
LatestPeriodOrHighestSystem
EarliestEpochOrLowestSeries
LatestEpochOrHighestSeries
EarliestAgeOrLowestStage
LatestAgeOrHighestStage
LowestBiostratigraphicZone
HighestBiostratigraphicZone
LithostratigraphicTerms
Group
Formation
Member
Bed
X identificationID
identifiedBy
X dateIdentified
identificationReferences
identificationRemarks
identificationQualifier
typeStatus
X taxonID
X scientificNameID
X acceptedNameUsageID
X parentNameUsageID
X originalNameUsageID
X nameAccordingToID
X namePublishedInID
X taxonConceptID
scientificName
acceptedNameUsage
parentNameUsage
originalNameUsage
nameAccordingTo
namePublishedIn
higherClassification
kingdom
phylum
class
order
family
genus
subgenus
specificEpithet
infraspecificEpithet
taxonRank
verbatimTaxonRank
scientificNameAuthorship
vernacularName
X nomenclaturalCode
taxonomicStatus
nomenclaturalStatus
taxonRemarks

**Comment by tucotuco** [comment]
Here is the list of fields again. On this list an X in front signifies that it is better to not be included in queriable fields:

type
X modified
language
X rights
X rightsHolder
X accessRights
X bibliographicCitation
X institutionID
X collectionID
X datasetID
institutionCode
collectionCode
datasetName
ownerInstitutionCode
basisOfRecord
X informationWithheld
X dataGeneralizations
(special) dynamicProperties
X occurrenceID
catalogNumber
X occurrenceDetails
X occurrenceRemarks
recordNumber
recordedBy
X individualID
X individualCount
sex
lifeStage
reproductiveCondition
behavior
establishmentMeans
occurrenceStatus
X preparations
X disposition
X otherCatalogNumbers
X previousIdentifications
X associatedMedia
X associatedReferences
X associatedOccurrences
X associatedSequences
X associatedTaxa
X eventID
samplingProtocol
samplingEffort
X eventDate
X eventTime
startDayOfYear
endDayOfYear
year
month
day
verbatimEventDate
X habitat
fieldNumber
X fieldNotes
X eventRemarks
X locationID
X higherGeographyID
X higherGeography
continent
waterBody
islandGroup
island
country
countryCode
stateProvince
county
municipality
locality
verbatimLocality
verbatimElevation
minimumElevationInMeters
maximumElevationInMeters
verbatimDepth
minimumDepthInMeters
maximumDepthInMeters
minimumDistanceAboveSurfaceInMeters
maximumDistanceAboveSurfaceInMeters
locationAccordingTo
X locationRemarks
X verbatimCoordinates
X verbatimLatitude
X verbatimLongitude
verbatimCoordinateSystem
verbatimSRS
decimalLatitude
decimalLongitude
geodeticDatum
coordinateUncertaintyInMeters
coordinatePrecision
X pointRadiusSpatialFit
X footprintWKT
X footprintSRS
X footprintSpatialFit
georeferencedBy
georeferenceProtocol
X georeferenceSources
georeferenceVerificationStatus
X georeferenceRemarks
X geologicalContextID
EarliestEonOrLowestEonothem
LatestEonOrHighestEonothem
EarliestEraOrLowestErathem
LatestEraOrHighestErathem
EarliestPeriodOrLowestSystem
LatestPeriodOrHighestSystem
EarliestEpochOrLowestSeries
LatestEpochOrHighestSeries
EarliestAgeOrLowestStage
LatestAgeOrHighestStage
LowestBiostratigraphicZone
HighestBiostratigraphicZone
LithostratigraphicTerms
Group
Formation
Member
Bed
X identificationID
identifiedBy
X dateIdentified
X identificationReferences
X identificationRemarks
identificationQualifier
typeStatus
X taxonID
X scientificNameID
X acceptedNameUsageID
X parentNameUsageID
X originalNameUsageID
X nameAccordingToID
X namePublishedInID
X taxonConceptID
scientificName
acceptedNameUsage
parentNameUsage
originalNameUsage
nameAccordingTo
X namePublishedIn
X higherClassification
kingdom
phylum
class
order
family
genus
subgenus
specificEpithet
infraspecificEpithet
taxonRank
verbatimTaxonRank
scientificNameAuthorship
vernacularName
nomenclaturalCode
taxonomicStatus
nomenclaturalStatus
X taxonRemarks

**Comment by eightysteele** [comment]
Gist with all stop words specified by @tucotuco: https://gist.github.com/1129865

**Comment by eightysteele** [comment]
@tucotuco: Is there a strong reason for not indexing `occurrenceid`? Seems like a common use case. Same for all id fields (`institutionid` et al).

**Comment by tucotuco** [comment]
Well, I was thinking they are huge, but yeah, if we start getting "linked in" (Linked Open Data), then they will be useful.

**Comment by eightysteele** [comment]
In the meantime I removed just `occurrenceid` from the do not index list and we can remove others as needed. All good?

**Comment by tucotuco** [comment]
Sounds fine. Just make sure it isn't populated with the sourceid unless the sourceid really is the occurrenceid (persistent resolvable, GUID).

**Comment by eightysteele** [comment]
> Just make sure it isn't populated with the sourceid unless the sourceid really is the occurrenceid (persistent resolvable, GUID).

Yeah, this is just indexing. Has nothing to do with `sourceid` stuff from issue #1.
