### ISSUE TITLE
Transfer App Engine billing to project

### ISSUE THREAD

**Issue by eightysteele** [VertNet/Darwin-Core-Engine#19]
@tucotuco: What's the status on how we're going to handle this?

**Comment by datadavev** [comment]
The simplest approach for now will be to let the service be at the mercy of the app engine free quota limits. If we find that is a significant issue, then we'll have to find a way to cover costs.

**Comment by eightysteele** [comment]
@vdave: Totally agree, but oops, I already went over the free quota on CPU for being trigger happy on MapReduce jobs to clear the datastore. Short term I signed up for billing and can probably get reimbursed by VertNet for the 2 or 3 dollars. Maybe?

**Comment by datadavev** [comment]
Yes, of course. Just forward pdf of the receipt app engine will send you.

**Comment by eightysteele** [comment]
> Yes, of course. Just forward pdf of the receipt app engine will send you.

+1

In the meantime we'll still need a longer term solution for transferring billing to a VertNet Google Checkout account or something.
