### ISSUE TITLE
Ping integration partners on API design

### ISSUE THREAD

**Issue by eightysteele** [VertNet/Darwin-Core-Engine#29]
Seek feedback on design, usability, etc.

**Comment by eightysteele** [comment]
@dbloom: Do we have a contact list for our integration partners?

**Comment by dbloom** [comment]
Only email addresses.

Arctos = Dusty McDonald" dustymc@gmail.com

AWeb = Joyce Gross joyceg@berkeley.edu

Specify = Tim Noble timo@ku.edu

Map of Life = you know these guys pretty well, but guess we should include
Rob as the contact.

GEOLocate = Nelson Rios nelson@museum.tulane.edu

**Comment by eightysteele** [comment]
+1

**Comment by eightysteele** [comment]
Done: https://groups.google.com/d/topic/vertnet-developers/5wLdfh3E8-s/discussion

Closing issue.
