### ISSUE TITLE
Changes to dce.py publishing options

### ISSUE THREAD

**Issue by tucotuco** [VertNet/Darwin-Core-Engine#49]
Deletes are a problem.

Data provider should be able to specify what to do on a by-csv-file basis:

-add: add or update everything in this file, no deletes please
-delete: mark everything in this file for deletion
-sync: make the database look like this

**Comment by eightysteele** [comment]
Deletes are definitely a problem. I'm thinking as a first pass maybe we make it even more simple with just a `./engine.py delete -f data.csv` command that deletes all records in a CSV file from both App Engine and the local sqlite3 database. Maybe?

**Comment by tucotuco** [comment]
I see no problem with that. I like the direct aspect of it. In fact, I kinda prefer that mode for all operations.
