### ISSUE TITLE
API base url

### ISSUE THREAD

**Issue by sckott** [VertNet/Darwin-Core-Engine#55]
After looking at the prototype search API, I don't see a base url to build the query to the API on top of. I'm not sure where to look for this url.

**Comment by eightysteele** [comment]
@SChamberlain: Yeah, here's our canary base URL for testing the API:

http://canary.vert-net.appspot.com/api/search

We have about 1000 records there. Here's an example request for birds in California:

http://canary.vert-net.appspot.com/api/search?cl=aves&sp=california&limit=1

Note that we _just_ updated our prototype search API wiki page with new information about using Darwin Core short names as query parameters. We've also changed the JSON response format a bit, and the `offset` parameter is now provided in the response as `next_offset`. 

https://github.com/VertNet/Darwin-Core-Engine/wiki/Prototype-Search-API
